skip_branch_with_pr: true

environment:
  HOME: $(HOMEDRIVE)$(HOMEPATH)

cache:
  - $(HOME)\.gradle\caches
  - $(HOME)\.gradle\wrapper\dists -> gradle\wrapper\gradle-wrapper.properties

build_script:
  - gradlew assemble

test_script:
  - gradlew check

after_test:
  - gradlew --stop

on_finish:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $pattern = 'build\test-results\**\TEST-*.xml'
      foreach ($file in (Resolve-Path $pattern)) {
        (New-Object 'System.Net.WebClient').UploadFile($url, $file)
      }
